// <auto-generated />
using System;
using HategIsland___API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HategIsland___API.Migrations
{
    [DbContext(typeof(HategIslandContext))]
    [Migration("20211203003440_Inital")]
    partial class Inital
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HategIsland___API.Models.Battle", b =>
                {
                    b.Property<int>("BattleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CurrentPlayerTurn")
                        .HasColumnType("int");

                    b.Property<int>("InitiatingPlayerID")
                        .HasColumnType("int");

                    b.Property<string>("InitiatingPlayerPack")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PlayerID")
                        .HasColumnType("int");

                    b.Property<int>("ReceivingPlayerID")
                        .HasColumnType("int");

                    b.Property<string>("ReceivingPlayerPack")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Winner")
                        .HasColumnType("int");

                    b.HasKey("BattleID");

                    b.HasIndex("PlayerID");

                    b.ToTable("Battles");
                });

            modelBuilder.Entity("HategIsland___API.Models.DinosaurSpecies", b =>
                {
                    b.Property<int>("DinosaurSpeciesID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AOH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BaseHealth")
                        .HasColumnType("int");

                    b.Property<int>("BaseHunger")
                        .HasColumnType("int");

                    b.Property<int>("BaseStamina")
                        .HasColumnType("int");

                    b.Property<int>("BaseThirst")
                        .HasColumnType("int");

                    b.Property<string>("Diet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HistoricalBlurb")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Size")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Species")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DinosaurSpeciesID");

                    b.ToTable("DinosaurSpecies");

                    b.HasData(
                        new
                        {
                            DinosaurSpeciesID = 1,
                            AOH = "",
                            BaseHealth = 0,
                            BaseHunger = 100,
                            BaseStamina = 0,
                            BaseThirst = 100,
                            Diet = "",
                            HistoricalBlurb = "",
                            Size = "",
                            Species = ""
                        },
                        new
                        {
                            DinosaurSpeciesID = 2,
                            AOH = "Air",
                            BaseHealth = 50,
                            BaseHunger = 100,
                            BaseStamina = 30,
                            BaseThirst = 100,
                            Diet = "Carnivore",
                            HistoricalBlurb = "A small flying reptile, the Pterodactylus was alive during the late Jurassic Period around Europe and Africa. It is a generalist carnivore that feeds on a variety of invertebrates and vertebrates. Its body is roughly the size of a house cat with a wingspan around 1.04m.",
                            Size = "Small",
                            Species = "Pterodactylus"
                        },
                        new
                        {
                            DinosaurSpeciesID = 3,
                            AOH = "Air",
                            BaseHealth = 50,
                            BaseHunger = 100,
                            BaseStamina = 30,
                            BaseThirst = 100,
                            Diet = "Carnivore",
                            HistoricalBlurb = "A small flying reptile, the Dimorphodon was alive during the early Jurassic Period. Inhabiting the European Continent, this pterosaur had a body length from 1m to 1.5m. Whilst able to fly, its aerodynamics do not support long distance flight and it relies on short hops. It is a fantastic climber. Whilst classified as a carnivore its diet is more closer to a scavengers diet, eating anything from plants and insects to fish and small rodents.",
                            Size = "Small",
                            Species = "Dimorphodon"
                        },
                        new
                        {
                            DinosaurSpeciesID = 4,
                            AOH = "Air",
                            BaseHealth = 50,
                            BaseHunger = 100,
                            BaseStamina = 30,
                            BaseThirst = 100,
                            Diet = "Carnivore",
                            HistoricalBlurb = "A tiny flying dinosaur that lived during the late Jurassic Period. This bat like creature hunted mostly insects and smaller prey. Its large eyes give it phenomnial eyesight.",
                            Size = "Small",
                            Species = "Anurognathus"
                        },
                        new
                        {
                            DinosaurSpeciesID = 5,
                            AOH = "Air",
                            BaseHealth = 75,
                            BaseHunger = 100,
                            BaseStamina = 30,
                            BaseThirst = 100,
                            Diet = "Carnivore",
                            HistoricalBlurb = "A medium flying reptile, the Kryptodrakon is one of the oldest known pterodactyloid pterosaurs living from the middle to late Jurassic Period. Inhabiting what is now known as modern day China, this dinosaur has a wingspan around 1.5m. The crest on its head is used for speech and calls.",
                            Size = "Medium",
                            Species = "Kryptodrakon"
                        },
                        new
                        {
                            DinosaurSpeciesID = 6,
                            AOH = "Air",
                            BaseHealth = 75,
                            BaseHunger = 100,
                            BaseStamina = 30,
                            BaseThirst = 100,
                            Diet = "Herbivore",
                            HistoricalBlurb = "This medium flying reptile can grow a wingspan of around 2.5m. Its most prominent feature is its mouth where a series of bristle-like teeth line its lower jaw. It is theorised that its diet consisted partly of crustaceans and as a result, like the flamingo, its feathered skin was most likely a pinkish hue.",
                            Size = "Medium",
                            Species = "Pterodaustro"
                        },
                        new
                        {
                            DinosaurSpeciesID = 7,
                            AOH = "Air",
                            BaseHealth = 75,
                            BaseHunger = 100,
                            BaseStamina = 30,
                            BaseThirst = 100,
                            Diet = "Carnivore",
                            HistoricalBlurb = "This medium sized flying reptile can grow a wingspan of around 4m. Its arrowhead like skull allows it to glide through the air with ease. It lived during the late Cretaceous Period in the area known today as Hungary.",
                            Size = "Medium",
                            Species = "Bakonydraco"
                        },
                        new
                        {
                            DinosaurSpeciesID = 8,
                            AOH = "Air",
                            BaseHealth = 100,
                            BaseHunger = 100,
                            BaseStamina = 30,
                            BaseThirst = 100,
                            Diet = "Carnivore",
                            HistoricalBlurb = "This large flying dinosaur lived during the late Cretaceous Period within North America. It has been known as one of the largest flying animals to have ever existed. Its wingspan can range from 11m up to 20m. When standing on its legs it can reach a height of 3m. This dinosaur primarlly eats small vertebrates and can be teritorial in its hunting areas.",
                            Size = "Large",
                            Species = "Quetzalcoatlus"
                        },
                        new
                        {
                            DinosaurSpeciesID = 9,
                            AOH = "Air",
                            BaseHealth = 100,
                            BaseHunger = 100,
                            BaseStamina = 30,
                            BaseThirst = 100,
                            Diet = "Carnivore",
                            HistoricalBlurb = "The Tupandactylus was a large pterosaur that lived in the early Cretaceous Period. Its wingspan can be up to 5m across and its most noticable feature is its large crainial crest. This crest, composed partly of bone and soft tissue, is used to signal to others as well as a means of determining wing speed and other flight measurements.",
                            Size = "Large",
                            Species = "Tupandactylus"
                        },
                        new
                        {
                            DinosaurSpeciesID = 10,
                            AOH = "Air",
                            BaseHealth = 100,
                            BaseHunger = 100,
                            BaseStamina = 30,
                            BaseThirst = 100,
                            Diet = "Carnivore",
                            HistoricalBlurb = "From the late Cretaceous Period, Geosternbergia is among the largest of the pterosaurs with its wingspan ranging from 3m to 6m. Its extended beak holds no teeth, an unusual trait for most flying dinosaurs.",
                            Size = "Large",
                            Species = "Geosternbergia"
                        },
                        new
                        {
                            DinosaurSpeciesID = 11,
                            AOH = "Air",
                            BaseHealth = 100,
                            BaseHunger = 100,
                            BaseStamina = 30,
                            BaseThirst = 100,
                            Diet = "Carnivore",
                            HistoricalBlurb = "Native to Brazil, the Tropeognathus is one of the largest pterosaurs with a wing span of 8m and upwards. Its most noticable feature is the crest on their snout. This spoon like structure allows the creature to fish prey from deeper in the water than other winged counterparts.",
                            Size = "Large",
                            Species = "Tropeognathus"
                        },
                        new
                        {
                            DinosaurSpeciesID = 12,
                            AOH = "Land",
                            BaseHealth = 50,
                            BaseHunger = 100,
                            BaseStamina = 30,
                            BaseThirst = 100,
                            Diet = "Herbivore",
                            HistoricalBlurb = "The Pisanosaurus lived in Northwestern Argentina during the later Triassic Period. This small feathered herbivore reaches 1m in length and weighs around 5-10kg. Its diet consistes primarilly of ferns, conifers, and other leafy greens but have been noted to enjoy insects as well.",
                            Size = "Small",
                            Species = "Pisanosaurus"
                        },
                        new
                        {
                            DinosaurSpeciesID = 13,
                            AOH = "Land",
                            BaseHealth = 50,
                            BaseHunger = 100,
                            BaseStamina = 30,
                            BaseThirst = 100,
                            Diet = "Herbivore",
                            HistoricalBlurb = "In the Arizona plains during the early Jurassic Period this small armored herbivore ran amuck. Its name translating in latin to \"little - shielded lizard\" provides detail for the several hundred bone seams running along its back. This creature is very social and works well together in packs.",
                            Size = "Small",
                            Species = "Scutellosaurus"
                        },
                        new
                        {
                            DinosaurSpeciesID = 14,
                            AOH = "Land",
                            BaseHealth = 50,
                            BaseHunger = 100,
                            BaseStamina = 30,
                            BaseThirst = 100,
                            Diet = "Herbivore",
                            HistoricalBlurb = "Part weasel, part chicken: the Fruitaden grows to 75cm in length and weighs around 0.75kg. This very small dinosaur is oppourtinistic in its diet, eating whatever it can find but prefers to eat plant materials. Historically found during the late Jurassic Period in Colorado.",
                            Size = "Small",
                            Species = "Fruitadens"
                        },
                        new
                        {
                            DinosaurSpeciesID = 15,
                            AOH = "Land",
                            BaseHealth = 50,
                            BaseHunger = 100,
                            BaseStamina = 30,
                            BaseThirst = 100,
                            Diet = "Herbivore",
                            HistoricalBlurb = "This furry creature from the late Jurassic Period in China is most noticable due to its feathered back spine. Living most of its life on the ground, the Tianyulong has been found to burrow underground and nest.",
                            Size = "Small",
                            Species = "Tianyulong"
                        },
                        new
                        {
                            DinosaurSpeciesID = 16,
                            AOH = "Land",
                            BaseHealth = 50,
                            BaseHunger = 100,
                            BaseStamina = 30,
                            BaseThirst = 100,
                            Diet = "Carnivore",
                            HistoricalBlurb = "During the late Triassic Period in North America the Camposaurus hunted small vertibrates, insects, and fish. These tiny creatures scavenged whatever they can find but eat primarilly meat.",
                            Size = "Small",
                            Species = "Camposaurus"
                        },
                        new
                        {
                            DinosaurSpeciesID = 17,
                            AOH = "Land",
                            BaseHealth = 50,
                            BaseHunger = 100,
                            BaseStamina = 30,
                            BaseThirst = 100,
                            Diet = "Carnivore",
                            HistoricalBlurb = "Perhaps the smallest dinosaur known, the Juravenator grew up to 75cm long and lived during the late Jurassic Period. This tiny creature has a fine coat of feathers as well as scales, and behaves very similarly to ducks.",
                            Size = "Small",
                            Species = "Juravenator"
                        },
                        new
                        {
                            DinosaurSpeciesID = 18,
                            AOH = "Land",
                            BaseHealth = 50,
                            BaseHunger = 100,
                            BaseStamina = 30,
                            BaseThirst = 100,
                            Diet = "Carnivore",
                            HistoricalBlurb = "Using its slender snout and powerful arms to eat insects, the Albertonykus was found throughout North American during the late Cretaceous Period. Originally thought to only eat insects, we have since discovered that it can also hunt small vertibrates with its extremelly powerful limbs.",
                            Size = "Small",
                            Species = "Albertonykus"
                        },
                        new
                        {
                            DinosaurSpeciesID = 19,
                            AOH = "Land",
                            BaseHealth = 75,
                            BaseHunger = 100,
                            BaseStamina = 30,
                            BaseThirst = 100,
                            Diet = "Herbivore",
                            HistoricalBlurb = "The famous Stegosaurus lived during the late Jurassic Period. With its distinctive kite shaped plates along its spine and spikes protruding from its tail; this magnificent dinosaur has been prominent throughout pop culture. The Stegosaurus is a pack herbiovre and its diet consistets of low lying fauna like ferns and shrubs.",
                            Size = "Medium",
                            Species = "Stegosaurus"
                        },
                        new
                        {
                            DinosaurSpeciesID = 20,
                            AOH = "Land",
                            BaseHealth = 75,
                            BaseHunger = 100,
                            BaseStamina = 30,
                            BaseThirst = 100,
                            Diet = "Herbivore",
                            HistoricalBlurb = "If dinosaurs could be considered stubborn, the Pachycephalosaurus would be the most hard headed of them all, literally. This medium dinosaur features a skull with an extensively thick roof used for defensive and social purposes. Its diet is also unique amongst dinosaurs in that whilst it is a herbivore, it doesnt eat fibrous materials but prefers to eat seeds, leaves, and fruit.",
                            Size = "Medium",
                            Species = "Pachycephalosaurus"
                        },
                        new
                        {
                            DinosaurSpeciesID = 21,
                            AOH = "Land",
                            BaseHealth = 75,
                            BaseHunger = 100,
                            BaseStamina = 30,
                            BaseThirst = 100,
                            Diet = "Herbivore",
                            HistoricalBlurb = "A living tank: The Ankylosaurus was a heavily armoured dinosaur with heavy bone plates over its body and an offensive club on the end of its tail. This dinosaur could grow to 6-8m and weighed from 4.8 to 8 metric tonnes. Whilst a social creature, the Ankylosaurus preferes to be amongst its kind and has difficulty working with others.",
                            Size = "Medium",
                            Species = "Ankylosaurus"
                        },
                        new
                        {
                            DinosaurSpeciesID = 22,
                            AOH = "Land",
                            BaseHealth = 75,
                            BaseHunger = 100,
                            BaseStamina = 30,
                            BaseThirst = 100,
                            Diet = "Herbivore",
                            HistoricalBlurb = "With its two horns protuding from its head, the Triceratops lived during the late Cretaceous Period in North America. This distinct looking dinosaur has been known to grow up to 9m long and weighing 12 metric tonnes. Its horns are used for both social and defensive purposes. The Triceratops enjoys co-habitating with other dinosaurs and has been observed to act defensively for the benefit of other dinosaurs.",
                            Size = "Medium",
                            Species = "Triceratops"
                        },
                        new
                        {
                            DinosaurSpeciesID = 23,
                            AOH = "Land",
                            BaseHealth = 75,
                            BaseHunger = 100,
                            BaseStamina = 30,
                            BaseThirst = 100,
                            Diet = "Herbivore",
                            HistoricalBlurb = "With its notable crest extending backward from its head, the Parasaurolophus lived during the late Cretaceous Period. A herbivore grazing amongst the ground level fauna as well as shorter trees and tall shrubs. This dinosaur moves in herds utilising its hollow crest to communicate with others of its kind.",
                            Size = "Medium",
                            Species = "Parasaurolophus"
                        },
                        new
                        {
                            DinosaurSpeciesID = 24,
                            AOH = "Land",
                            BaseHealth = 75,
                            BaseHunger = 100,
                            BaseStamina = 30,
                            BaseThirst = 100,
                            Diet = "Carnivore",
                            HistoricalBlurb = "A close relative of the Dilophosaurus, the Dracovenator measures up to 7m in length and features a protuding dual horn on its head. This dinosaur is difficult to tame and is often overcome by instinctual impulses.",
                            Size = "Medium",
                            Species = "Dracovenator"
                        },
                        new
                        {
                            DinosaurSpeciesID = 25,
                            AOH = "Land",
                            BaseHealth = 75,
                            BaseHunger = 100,
                            BaseStamina = 30,
                            BaseThirst = 100,
                            Diet = "Carnivore",
                            HistoricalBlurb = "Ozraptor: def \"Australian Thief\". This dinosaur, native to the area known today as Australia, lived during the middle Jurassic Period. This keen predator measures up to 3m in length and can reach speeds of 40km/hr. Although a solitary hunter, it is able to work with others of its kind to reach a shared goal.",
                            Size = "Medium",
                            Species = "Ozraptor"
                        },
                        new
                        {
                            DinosaurSpeciesID = 26,
                            AOH = "Land",
                            BaseHealth = 75,
                            BaseHunger = 100,
                            BaseStamina = 30,
                            BaseThirst = 100,
                            Diet = "Carnivore",
                            HistoricalBlurb = "During the late Triassic Period in South America, the Herrerasaurus roamed hunting for its prey. This vicious carnivore can grow up to 6m in length and weighing nearly 400kg. They are a fully bipedal creature which allows them to reach fast speeds to track and kill its prey.",
                            Size = "Medium",
                            Species = "Herrerasaurus"
                        },
                        new
                        {
                            DinosaurSpeciesID = 27,
                            AOH = "Land",
                            BaseHealth = 75,
                            BaseHunger = 100,
                            BaseStamina = 30,
                            BaseThirst = 100,
                            Diet = "Carnivore",
                            HistoricalBlurb = "This dinosaur native to the Japanese landmass is known for its terrifying bloodlust. Living during the early Cretaceous Period, this dinosaur has been witnessed to show a keen skill for hunting its prey. It takes keen interest in vertibrates smaller than its average size of 4.5m long.",
                            Size = "Medium",
                            Species = "Fukuiraptor"
                        },
                        new
                        {
                            DinosaurSpeciesID = 28,
                            AOH = "Land",
                            BaseHealth = 100,
                            BaseHunger = 100,
                            BaseStamina = 30,
                            BaseThirst = 100,
                            Diet = "Herbivore",
                            HistoricalBlurb = "The Muttaburrasaurus was alive during the early Cretaceous Period in the grassy plains of Australia. This fasinating creature is most discernable by its pointed snout bone protuding upwards. This hollow cavity allows it to make deafining social calls but also provides the creature a remarkable sense of smell, being able to distinguish predators from over 5kms away. Measuring on average 8m in length and nearly 3 tonnes, these big herbivores are a wonderful sight to see.",
                            Size = "Large",
                            Species = "Muttaburrasaurus"
                        },
                        new
                        {
                            DinosaurSpeciesID = 29,
                            AOH = "Land",
                            BaseHealth = 100,
                            BaseHunger = 100,
                            BaseStamina = 30,
                            BaseThirst = 100,
                            Diet = "Herbivore",
                            HistoricalBlurb = "Its name preceeds the creature, the famous Brachiosaurus, is a delight for the eyes. This huge herbivore can grow anywhere from 10m to 20m in length and weighs in at an average of 38 metric tonnes. Its long neck distinguishes it from most other dinosaurs but youll be able to hear its distinictive social call from kilometers away. Utilising the air sacs throughout its neck to create the low rumble it uses to communicate.",
                            Size = "Large",
                            Species = "Brachiosaurus"
                        },
                        new
                        {
                            DinosaurSpeciesID = 30,
                            AOH = "Land",
                            BaseHealth = 100,
                            BaseHunger = 100,
                            BaseStamina = 30,
                            BaseThirst = 100,
                            Diet = "Herbivore",
                            HistoricalBlurb = "Able to walk on all 4's but run on its two powerful back legs, the Edmontosaurus is a fascinating herbivore. Living during the late Cretacarous throughout the American Landmass, this dinosaur has been noted to migrate and prefers costal areas. Its most distingusihing feature is its bent neck which allows the Edmontosaurus to participate in jousting like behaviours as a social activity to determine dominance.",
                            Size = "Large",
                            Species = "Edmontosaurus"
                        },
                        new
                        {
                            DinosaurSpeciesID = 31,
                            AOH = "Land",
                            BaseHealth = 100,
                            BaseHunger = 100,
                            BaseStamina = 30,
                            BaseThirst = 100,
                            Diet = "Herbivore",
                            HistoricalBlurb = "Nice dinosaur you have there, it'd be a shame if mine were bigger - oh wait… The Sauroposeidon is possibly the largest dinosaur ever to have walked the earth. Its head can reach a mind boggling height of 18m above the ground (that’s around the height of a six story building) and weighing a gargantuan weight of 60 tonnes, this creature has been considered by some academics as: \"kinda big I guess\". What makes this creature truly remarkable however is just how much food it can consume as well as the sheer variety of sustience it is willing to consume.",
                            Size = "Large",
                            Species = "Sauroposeidon"
                        },
                        new
                        {
                            DinosaurSpeciesID = 32,
                            AOH = "Land",
                            BaseHealth = 100,
                            BaseHunger = 100,
                            BaseStamina = 30,
                            BaseThirst = 100,
                            Diet = "Carnivore",
                            HistoricalBlurb = "A ferocious predator, Ceratosaurus was alive during the late Jurassic Period. Its most distinctive features, the protuding snout bones, are used as fearsome weapons in blunt force attacks as well as in social engagements for dominance. This creature engages is constant grooming to ensure that the horns are kept strong and ready.",
                            Size = "Large",
                            Species = "Ceratosaurus"
                        },
                        new
                        {
                            DinosaurSpeciesID = 33,
                            AOH = "Land",
                            BaseHealth = 100,
                            BaseHunger = 100,
                            BaseStamina = 30,
                            BaseThirst = 100,
                            Diet = "Carnivore",
                            HistoricalBlurb = "Native to the land that is now India, the Majungasaurus hunted for prey during the late Cretacaous Period. Don't be mistaken by its comparatively short and blunt snout, this dinosaur can and will eat you if given the opportunity. Its diet has beennoted to be so varied that it can and often will engage in cannibalism by hunting and eating others of its own kind.",
                            Size = "Large",
                            Species = "Majungasaurus"
                        },
                        new
                        {
                            DinosaurSpeciesID = 34,
                            AOH = "Land",
                            BaseHealth = 100,
                            BaseHunger = 100,
                            BaseStamina = 30,
                            BaseThirst = 100,
                            Diet = "Carnivore",
                            HistoricalBlurb = "Often mistaken for a fan or sail boat, the Spinosaurus is actully neither. This dinosaur lived during the late Cretaceous Period and can grow to sizes upwards of 15m long. Along the spine of the dinosaur is its distinctive sail used for heat regulation, intimidation of prey, and balance in and out of the water. Spinosaurus is similar in its behaviour to that of a crocodile, spending a large portion of its time in the water but also able to hunt on land. Its diet consistes of terristal and aquatic animals but it particularly enjoys eating people that make fun of its spine.",
                            Size = "Large",
                            Species = "Spinosaurus"
                        },
                        new
                        {
                            DinosaurSpeciesID = 35,
                            AOH = "Land",
                            BaseHealth = 100,
                            BaseHunger = 100,
                            BaseStamina = 30,
                            BaseThirst = 100,
                            Diet = "Carnivore",
                            HistoricalBlurb = "An unexpectedly social creature, the Allosaurus lived and hunted in packs during the late Jurassic Period. This predator works together to herd prey into small confined areas and then slowly weakens the animal over an extended period of time. This hunting behaviour has been regarded as highly advanced amongst dinosaurs and should not be underestimated.",
                            Size = "Large",
                            Species = "Allosaurus"
                        },
                        new
                        {
                            DinosaurSpeciesID = 36,
                            AOH = "Land",
                            BaseHealth = 100,
                            BaseHunger = 100,
                            BaseStamina = 30,
                            BaseThirst = 100,
                            Diet = "Carnivore",
                            HistoricalBlurb = "Ruler of the dinosaurs, the Tyrannosaurus has been portrayed throughout culture as a fearsome predator that roamed North America during the late Cretaceous Period. The reality of this dinosaur is much more terrifying, able to view and track prey accuratley from a distance of 6km (humans can only see 1.6km). This creature can track scents through all terrain types over extremely long distances rivally that of the vulture. The Tyrannosaurus is also able to hear low-frequency noises with astonishing accuracy and its skin is highly sensitive to temperature fluctuations around providing it the ability to track smaller close prey outside of its other senses. This dinsoaur is arguably the most advanced hunting creature ever to roam the planet.",
                            Size = "Large",
                            Species = "Tyrannosaurus"
                        },
                        new
                        {
                            DinosaurSpeciesID = 37,
                            AOH = "Water",
                            BaseHealth = 50,
                            BaseHunger = 100,
                            BaseStamina = 30,
                            BaseThirst = 100,
                            Diet = "Carnivore",
                            HistoricalBlurb = "During the late Triassic Period, of the coast of modern day California, these large fish-like reptiles hunted small fish and other marine creatures. Whilst generally unremarkable, the Californosaurus is a highly efficent and fast swimmer. This creature has been found to reach speeds of 35km/hr underwater. It utilises is sonar sense to communicate with others of its kind and is generally a social creature.",
                            Size = "Small",
                            Species = "Californosaurus"
                        },
                        new
                        {
                            DinosaurSpeciesID = 38,
                            AOH = "Water",
                            BaseHealth = 75,
                            BaseHunger = 100,
                            BaseStamina = 30,
                            BaseThirst = 100,
                            Diet = "Carnivore",
                            HistoricalBlurb = "Growing to an average length of 7m, the Platypteryguis navigated the waters around modren day Australia during the Cretaceous Period. This creture boasts a long snout and extremelly powerful tail. Originally thought to only eat marine animals, it has been found to hunt birds and pterosaurs flying low to the water. Utilising its powerful tail to launch itself up to 10m in the air, this stealthy hunter can strike at any unsuspecting flying prey.",
                            Size = "Medium",
                            Species = "Platypterygius"
                        },
                        new
                        {
                            DinosaurSpeciesID = 39,
                            AOH = "Water",
                            BaseHealth = 75,
                            BaseHunger = 100,
                            BaseStamina = 30,
                            BaseThirst = 100,
                            Diet = "Carnivore",
                            HistoricalBlurb = "Named after the famous sword, this swordfish like ichthyosaur can boast a 1.5m long snout at full maturity. The Excalibosaurus lurked in the early Jurassic Period waters of modern day England. Originally thought to be used for attacking and hunting purposes, the creatures snout is primarially used for coralling schools of fish with others of its kind. Working as a group, they will lead the fish towards the shallows and then utilise the limited space to eat their prey.",
                            Size = "Medium",
                            Species = "Excalibosaurus"
                        },
                        new
                        {
                            DinosaurSpeciesID = 40,
                            AOH = "Water",
                            BaseHealth = 75,
                            BaseHunger = 100,
                            BaseStamina = 30,
                            BaseThirst = 100,
                            Diet = "Carnivore",
                            HistoricalBlurb = "With its long slender neck and four flippers helping it to glide through the water seemingly efforlessly, the Attenborosaurus is a marvel to watch. This aquatic reptile was found in the early Jurassic Period in the waters around modern day England. Whilst it might seem calm in the water, it truly is a master of deception as this predator can lock on to its prey and is able to rapidly mobilise to hunt it down. Some have noted the level of intelligence displayed at times by this creature indicating that is capable of problem solving and reasoning to obtain its goals.",
                            Size = "Medium",
                            Species = "Attenborosaurus"
                        },
                        new
                        {
                            DinosaurSpeciesID = 41,
                            AOH = "Water",
                            BaseHealth = 100,
                            BaseHunger = 100,
                            BaseStamina = 30,
                            BaseThirst = 100,
                            Diet = "Carnivore",
                            HistoricalBlurb = "Growing up to 18m in length, this late Cretaceous reptile is a ferocious and intimidating creature. Hunting other marine reptiles and sharks this creature was a dominate force in the water. It has a powerful ability to see far distances within water and able to accuratly distinguish prey on the surface of the water. A monumental creature and highly effective underwater killing machine.",
                            Size = "Large",
                            Species = "Mosasaurus"
                        });
                });

            modelBuilder.Entity("HategIsland___API.Models.Inventory", b =>
                {
                    b.Property<int>("InventoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CarnFood")
                        .HasColumnType("int");

                    b.Property<int>("Herb")
                        .HasColumnType("int");

                    b.Property<int>("HerbFood")
                        .HasColumnType("int");

                    b.Property<int>("Medicine")
                        .HasColumnType("int");

                    b.Property<int>("Money")
                        .HasColumnType("int");

                    b.Property<int>("PlayerID")
                        .HasColumnType("int");

                    b.HasKey("InventoryID");

                    b.HasIndex("PlayerID")
                        .IsUnique();

                    b.ToTable("Inventories");
                });

            modelBuilder.Entity("HategIsland___API.Models.Location", b =>
                {
                    b.Property<int>("LocationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BaseDuration")
                        .HasColumnType("int");

                    b.Property<string>("BaseReward")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IndustryType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UnlockCost")
                        .HasColumnType("int");

                    b.HasKey("LocationID");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            LocationID = 1,
                            BaseDuration = 0,
                            BaseReward = "",
                            Description = "The birthplace of all your dinosaurs. This building houses all collected eggs and keeps them in optimum conditions until the little dinosaur inside is ready to join the world!",
                            IndustryType = "Base",
                            Name = "Hatchery",
                            UnlockCost = 0
                        },
                        new
                        {
                            LocationID = 2,
                            BaseDuration = 0,
                            BaseReward = "",
                            Description = "Wide open spaces, vast aveires, and deep lagoons. This is where your dinosaurs call home on Hateg Island, and there is plenty of fencing to ensure we keep the carnivores and herbivores separate.",
                            IndustryType = "Base",
                            Name = "Paddocks",
                            UnlockCost = 0
                        },
                        new
                        {
                            LocationID = 3,
                            BaseDuration = 0,
                            BaseReward = "",
                            Description = "Here you can send dinosaurs to battle against practice dummies and to increase their work ethic to help them at their jobs. By sending a dinosaur here you are helping it to become a better member of the Hateg Community by leveling up.",
                            IndustryType = "Base",
                            Name = "Training Arena",
                            UnlockCost = 0
                        },
                        new
                        {
                            LocationID = 4,
                            BaseDuration = 5,
                            BaseReward = "Herb#100#Money#300",
                            Description = "Dinosaurs spent millions of years helping the pre-historic forests regulate themselves by bringing trees down. Today, with the help of modern technology, we can utilise their unique abilities to assist us in cutting, hauling, and processing the timber to build or export.",
                            IndustryType = "Forestry",
                            Name = "Logging Camp",
                            UnlockCost = 1000
                        },
                        new
                        {
                            LocationID = 5,
                            BaseDuration = 5,
                            BaseReward = "Herb#150#Money#300",
                            Description = "Dinosaurs eat a lot and as a result all of that food needs to go somewhere once the dinosaur is done with it. By incorporating the proper seeds into their diet and letting them roam free, we have found that planting and nursing time for new forest areas is reduced dramatically.",
                            IndustryType = "Forestry",
                            Name = "Forestry Camp",
                            UnlockCost = 1250
                        },
                        new
                        {
                            LocationID = 6,
                            BaseDuration = 5,
                            BaseReward = "HerbFood#100#CarnFood#100",
                            Description = "Dinosaurs are innate at seeking out food and this is no different in the water. Using their fantastic eyesight and strength we can use them to spot fish and seaweed as well as help us haul it in.",
                            IndustryType = "Fishery",
                            Name = "Fishing Warf",
                            UnlockCost = 500
                        },
                        new
                        {
                            LocationID = 7,
                            BaseDuration = 15,
                            BaseReward = "HerbFood#500#CarnFood#500",
                            Description = "Why wait for the fish and seaweed to come to us, when we can go to them? AND bring the dinosaurs with us too! We've built a big platform about 3km off the coast of Hateg and we need some dinosaurs to help us find and haul the giant fish and seaweed loads.",
                            IndustryType = "Fishery",
                            Name = "Fishing Platform",
                            UnlockCost = 2500
                        },
                        new
                        {
                            LocationID = 8,
                            BaseDuration = 5,
                            BaseReward = "HerbFood#100#Money#150",
                            Description = "Humans have spent the last century inventing technologies to help us plant, grow, and harvest food more efficently. Well now we have creatures that have all the abilities of our technologies and can be trained not to drive into a ditch. Dinosaurs!",
                            IndustryType = "Agriculture",
                            Name = "Farming District",
                            UnlockCost = 500
                        },
                        new
                        {
                            LocationID = 9,
                            BaseDuration = 15,
                            BaseReward = "HerbFood#500#Money#300",
                            Description = "You've heard of the Paleo Diet right? Well turns out herbivore dinosaurs actually prefer the Paleo Diet! Humans like it, Dinosaurs like it, lets grow it!",
                            IndustryType = "Agriculture",
                            Name = "Paleo Farms",
                            UnlockCost = 2500
                        },
                        new
                        {
                            LocationID = 10,
                            BaseDuration = 5,
                            BaseReward = "CarnFood#100#Money#150",
                            Description = "Dinosaurs are surprisingly good at convincing other animals to walk in the opposite direction, who knew?! By using them in conjuction with livestock, we can increase our production of meat and animal products drastically!",
                            IndustryType = "Production",
                            Name = "Animal Husbandry District",
                            UnlockCost = 500
                        },
                        new
                        {
                            LocationID = 11,
                            BaseDuration = 15,
                            BaseReward = "CarnFood#500#Money#300",
                            Description = "Our lawyers would like us to read the following statement: \"Any dinosaurs leased to the Abattoir for labour purposes will be used in the production of any food products.\" Why use silly human means of producing meat when you can get dinosaurs to do it for you on a much larger scale?! Your dinosaur will be used to help create meat products and not themselves be made into meat products.",
                            IndustryType = "Production",
                            Name = "Abattoir",
                            UnlockCost = 2500
                        },
                        new
                        {
                            LocationID = 12,
                            BaseDuration = 5,
                            BaseReward = "Money#750",
                            Description = "We have a lot of industries all over the island and we need some way of moving them. Now we could use traditonal trucks or trains, but we have access to creatures that can be motivated to carry things and are intelligent enough to actually get from A to B. So, will that be air, land, or sea mail?",
                            IndustryType = "Distribution",
                            Name = "Postal Office",
                            UnlockCost = 4000
                        },
                        new
                        {
                            LocationID = 13,
                            BaseDuration = 20,
                            BaseReward = "Money#4000",
                            Description = "As Hateg gets bigger, a lot of our citizens want access to the resources other colonys are producing. We need some way of distributing all of the incoming goods around the island. It seems as usual, dinosaurs are the solution.",
                            IndustryType = "Distribution",
                            Name = "Customs Depot",
                            UnlockCost = 8000
                        },
                        new
                        {
                            LocationID = 14,
                            BaseDuration = 30,
                            BaseReward = "Money#6000",
                            Description = "Wow, we are sure getting a lot of people wanting to visit our island to see all the dinosaurs! Wouldn’t it be great if they had something else to do on the island though? An attraction where we could showcase a dinosaur or two!",
                            IndustryType = "Tourism",
                            Name = "Fair Ground",
                            UnlockCost = 10000
                        },
                        new
                        {
                            LocationID = 15,
                            BaseDuration = 45,
                            BaseReward = "Money#8000",
                            Description = "So, some billionare asked us if he could have a 5 star dinner on the island, we said we didn’t have anything like that. He said that he would heavily compensate building one and setting it up as long as he didn’t have to pay for staff. If only we had some creatures that could be trained to buss tables and take orders... Dinosaurs!",
                            IndustryType = "Tourism",
                            Name = "5 Star Restauraunt",
                            UnlockCost = 15000
                        },
                        new
                        {
                            LocationID = 16,
                            BaseDuration = 20,
                            BaseReward = "Herb#100",
                            Description = "Dinosaurs are remarkably good at diagnosis. They can cause…. *ahem* diagnose a wide range of bodily injuries. The local doctors clinic is the best place for them!",
                            IndustryType = "Healthcare",
                            Name = "Doctors Clinic",
                            UnlockCost = 4000
                        },
                        new
                        {
                            LocationID = 17,
                            BaseDuration = 20,
                            BaseReward = "",
                            Description = "Sometimes dinosaurs just cant walk it off and they need some urgent medical care from the best. That’s why we have our Dino Hospital with the best Paleo-Physicians on the island at the ready.",
                            IndustryType = "Healthcare",
                            Name = "Dino Hospital",
                            UnlockCost = 6000
                        });
                });

            modelBuilder.Entity("HategIsland___API.Models.LocationVisit", b =>
                {
                    b.Property<int>("LocationVisitID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CompletionReward")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DinosaurID")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("LocationID")
                        .HasColumnType("int");

                    b.Property<int>("PlayerID")
                        .HasColumnType("int");

                    b.HasKey("LocationVisitID");

                    b.HasIndex("LocationID");

                    b.HasIndex("PlayerID");

                    b.ToTable("LocationVisits");
                });

            modelBuilder.Entity("HategIsland___API.Models.PackedDinosaur", b =>
                {
                    b.Property<int>("PackedDinosaurID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Abilities")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DinosaurSpeciesID")
                        .HasColumnType("int");

                    b.Property<string>("Features")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlayerID")
                        .HasColumnType("int");

                    b.Property<string>("Stats")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Traits")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PackedDinosaurID");

                    b.HasIndex("DinosaurSpeciesID");

                    b.HasIndex("PlayerID");

                    b.ToTable("Dinosaurs");
                });

            modelBuilder.Entity("HategIsland___API.Models.Player", b =>
                {
                    b.Property<int>("PlayerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PlayerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnlockedLocations")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("PlayerID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            PlayerID = 1,
                            PlayerName = "DinoFan1",
                            UnlockedLocations = "1#2#3",
                            UserID = 1
                        });
                });

            modelBuilder.Entity("HategIsland___API.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Roles")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            Password = "$2b$10$M7U88LiQcylRnjbNx92SVuhuwpxjigDWXcTYuLBzRPdg78Mq/spNK",
                            Roles = "User, Admin",
                            Username = "Seb"
                        });
                });

            modelBuilder.Entity("HategIsland___API.Models.Battle", b =>
                {
                    b.HasOne("HategIsland___API.Models.Player", "Player")
                        .WithMany("Battles")
                        .HasForeignKey("PlayerID");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("HategIsland___API.Models.Inventory", b =>
                {
                    b.HasOne("HategIsland___API.Models.Player", "Player")
                        .WithOne("Inventory")
                        .HasForeignKey("HategIsland___API.Models.Inventory", "PlayerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("HategIsland___API.Models.LocationVisit", b =>
                {
                    b.HasOne("HategIsland___API.Models.Location", "Location")
                        .WithMany("LocationVisits")
                        .HasForeignKey("LocationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HategIsland___API.Models.Player", "Player")
                        .WithMany("LocationVisits")
                        .HasForeignKey("PlayerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("HategIsland___API.Models.PackedDinosaur", b =>
                {
                    b.HasOne("HategIsland___API.Models.DinosaurSpecies", "DinosaurSpecies")
                        .WithMany("Dinosaurs")
                        .HasForeignKey("DinosaurSpeciesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HategIsland___API.Models.Player", "Player")
                        .WithMany("Dinosaurs")
                        .HasForeignKey("PlayerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DinosaurSpecies");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("HategIsland___API.Models.Player", b =>
                {
                    b.HasOne("HategIsland___API.Models.User", "User")
                        .WithOne("Player")
                        .HasForeignKey("HategIsland___API.Models.Player", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HategIsland___API.Models.DinosaurSpecies", b =>
                {
                    b.Navigation("Dinosaurs");
                });

            modelBuilder.Entity("HategIsland___API.Models.Location", b =>
                {
                    b.Navigation("LocationVisits");
                });

            modelBuilder.Entity("HategIsland___API.Models.Player", b =>
                {
                    b.Navigation("Battles");

                    b.Navigation("Dinosaurs");

                    b.Navigation("Inventory");

                    b.Navigation("LocationVisits");
                });

            modelBuilder.Entity("HategIsland___API.Models.User", b =>
                {
                    b.Navigation("Player");
                });
#pragma warning restore 612, 618
        }
    }
}
